### ISSUE TITLE
[refactor] 자주 묻는 질문 Faq->ResponseDTO  전부 controller 에서만 사용하도록 수정

### ISSUE THREAD

**Issue by JeongByungJoo** [yanolja-finalproject/Backend#132]
## 설명
 현재 ResponseDTO가 Service와 Facade에 동시 적용되어 있는데, 관련 내용을 전부 Controller에서 처리할 수 있도록 수정

**Comment by deepredk** [comment]
@JeongByungJoo 완료한 이슈들 Close 부탁드립니다!
