### ISSUE TITLE
[Feat] 찜 기능 구현

### ISSUE THREAD

**Issue by windowM** [yanolja-finalproject/Backend#28]
## 설명
동시성 문제를 고려한 찜 기능 구현
Redis -> Redisson 라이브러리 이용 ([선택 이유](https://deeply-buttercup-ac1.notion.site/6d2772cdd0cf4b8990dfdf8d822b2990?pvs=4))

### 해야 할 것
* [ ] Redis 환경 구축
* [ ] 찜 기능 구현

### 기타
참고해야 할 사항이 있다면 댓글 남겨주세요!

**Comment by deepredk** [comment]
근데 찜에 동시성 이슈가 발생할 부분이 있나요??

**Comment by windowM** [comment]
순간적으로 찜 버튼을 2번 클릭하게 되면 발생하지 않나요?!

역할 전담 -> 혜미님
