### ISSUE TITLE
[Feature] GET /v1/search/options/destiantions 검색시 사용되는 옵션을 제공 - 여행지 목록(대륙,나라)

### ISSUE THREAD

**Issue by windowM** [yanolja-finalproject/Backend#55]
## 설명
- 검색시 사용되는 option을 제공하는 api (`v1/search/options/destinations`)

### 해야 할 것
- `v1/search/options` 응답에 담아야 할 값
  * [ ] 여행지 (destinations[])
    - 라벨에 노출될 이름 (optionNmae)
    - 나라 (nations[])
    - 대륙 (continents[]) 
    - 이미지

**Comment by deepredk** [comment]
@windowM 창호님 이슈 분리해주셔야 돼요! 단위가 너무 큽니다

**Comment by windowM** [comment]
@deepredk 해당 검색 기능이 GET으로 전부 묶이기도 하고 
issue가 너무 많은 것 보다 줄이는게 보기도 편하고 작업하기에도 편해 묶어두었는데, 분리해야할까요?

**Comment by deepredk** [comment]
@windowM
네 이거 한번에 진행하면
1. Files changed 50개는 나올 것 같고
2. Projects에서도 너무 길게 잡아야 해서요

**Comment by windowM** [comment]
수정완료
